name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'jaisalsrivastava'
          BLOG_URL: 'https://jaisalsrivastava.hashnode.dev' 
          COUNT: 4
          STYLE: "blog-grid"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
